### ISSUE TITLE
es5文件夹中的client.js需要timeout支持

### ISSUE THREAD

**Issue by yinhaijiao** [aliyun/api-gateway-nodejs-sdk#11]
在发送的数据较大或者网络不稳定的时候，需要延长timeout时间。
看了lib下的client.js里有timeout参数，但是在es5版本中并没有。
能否把es5中的timeout也加上，谢谢。

**Comment by JacksonTian** [comment]
重新生成并发布了。请适用最新的 1.1.1 版本
