### ISSUE TITLE
README.md is not right

### ISSUE THREAD

**Issue by ngogia20** [aliyun/api-gateway-nodejs-sdk#12]
In README.md client sample has

it('should ok get(url)', function* () {
  var url = 'https://dm-81.data.aliyun.com/rest/160601/ip/getIpInfo.json?ip=210.75.225.254';
  var result = yield client.get(url);
});

Issue raised and concern here - By Nikesh Gogia

1. **it** is not a correct variable. Can this be corrected ?
2. 'should ok get(url)' - Can you also correct this.

**Comment by JacksonTian** [comment]
It's a demo of unit tests that run with `mocha`. You can just use the generator block.

**Comment by JacksonTian** [comment]
The document was updated.
