### ISSUE TITLE
query DO not pass on post method

### ISSUE THREAD

**Issue by jazzhuang** [aliyun/api-gateway-nodejs-sdk#13]
https://github.com/aliyun/api-gateway-nodejs-sdk/blob/7b2c85edb9f397d7bff30f90984335d44c7133ff/lib/base.js#L74

url should be parsed

**Comment by jazzhuang** [comment]
put method has the same issue

**Comment by JacksonTian** [comment]
fixed via 4a49673b745e4710be89f6d69b8e2e3a60ed903c
