### ISSUE TITLE
build Failed to minify the code from this file

### ISSUE THREAD

**Issue by didmehh** [aliyun/api-gateway-nodejs-sdk#20]
报错信息:
```javascript
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/httpx/lib/index.js:53 

Read more here: http://bit.ly/2tRViJ9
```
 使用的`react`,脚手架是`create-react-app`.

出现这个问题,似乎是编译不通过.

[压缩出错解释](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify).

我打算尝试使用第三个方法来尝试解决.就是不知道出现这个问题,是因为什么原因.
是上面那样说的,因为没有预编译吗

**Comment by JacksonTian** [comment]
该模块不支持在前端使用。

**Comment by didmehh** [comment]
那就是没有适用前端的了吗?
