### ISSUE TITLE
Response with code 20x other 200 is thrown as error

### ISSUE THREAD

**Issue by aihornmac** [aliyun/api-gateway-nodejs-sdk#24]
Some of our APIs are returning 201 and 204 for POST and DELETE. After checking the source code, it appears that it accepts response only when code is 200, which should be an issue.

**Comment by JacksonTian** [comment]
Fixed in 94b8001163b0be97b8c775ac55bf6fb6b8018e82 .

**Comment by JacksonTian** [comment]
Please upgrade to newest version to use it.
