### ISSUE TITLE
在VUE中使用报错

### ISSUE THREAD

**Issue by way-Eric** [aliyun/api-gateway-nodejs-sdk#27]
![image](https://user-images.githubusercontent.com/31607719/63996358-0daebb80-cb2e-11e9-87c2-a665f1deae18.png)

找了也没有找到关于前端调用API网关sdk的文档和说明，好不容易找到，可以访问但是依赖内部报错，没法返回response

**Comment by sjhowyou** [comment]
兄弟，解决没！！！

**Comment by WangJunZzz** [comment]
在你的node_modules中有个httpx，注释调图中的就可以了.
![image](https://user-images.githubusercontent.com/25657426/65829907-e68a0c00-e2dc-11e9-84e0-52f1940f3fb8.png)

**Comment by peze** [comment]
由于 API Gateway 需要使用 AK 来实现签名，在浏览器场景下，极易容易产生安全性问题，因此本模块不支持在浏览器中使用。

**Comment by clarastar** [comment]
你好，有没有一个浏览器场景下的 api gateway 呢？

**Comment by DrLemonPie** [comment]
解决了，依赖的httpx的版本问题，你翻一下注册表同步一下httpx的版本，重装一下httpx

![Image](https://github.com/user-attachments/assets/9aa75fda-0ece-448d-9d9a-b6461dfae456)

![Image](https://github.com/user-attachments/assets/e4cfdc84-f114-435f-b655-41a4cc81116e)
