### ISSUE TITLE
请问如何通过node.js调用阿里云网关

### ISSUE THREAD

**Issue by ghost** [aliyun/api-gateway-nodejs-sdk#7]
请问如何通过node.js调用阿里云网关？Restful API

**Comment by JacksonTian** [comment]
这个 SDK 就是的呀。参见 README

**Comment by ghost** [comment]
请求方法不能put、delete

**Comment by JacksonTian** [comment]
给一下你的 API 定义，我帮你写 demo。

**Comment by ghost** [comment]
刚才看了源码，这个sdk要支持put,需要修改base.js对吗？

**Comment by JacksonTian** [comment]
哦，是没有留 PUT 的口子。

能否给出 API 定义？我改好，帮你写好demo给你。

**Comment by yangpengfei** [comment]
![image](https://user-images.githubusercontent.com/7697949/26864748-505709ca-4b8c-11e7-84b5-545fd959f6cd.png)

**Comment by ghost** [comment]
麻烦您啦

**Comment by JacksonTian** [comment]
请问是否有 IM？ 钉钉？旺旺？QQ？微信？我私下联系你下

**Comment by ghost** [comment]
好的，QQ289834894
